function TermCondition() {
  return (
    <div className="px-4 md:p-20">
      <div className="">
        <h1 className="text-4xl font-semibold">General Terms</h1>
        <p className="py-5 text-gray-700">
          "By accessing and placing an order with Freelancer, you confirm that
          you are in agreement with and bound by the terms of service contained
          in the Terms & Conditions outlined below. These terms apply to the
          entire website and any email or other type of communication between
          you and Freelancer."
        </p>
        <p className="py-3 text-gray-700">
          Under no circumstances shall Freelancer team be liable for any direct,
          indirect, special, incidental or consequential damages, including, but
          not limited to, loss of data or profit, arising out of the use, or the
          inability to use, the materials on this site, even if Freelancer team
          or an authorized representative has been advised of the possibility of
          such damages. If your use of materials from this site results in the
          need for servicing, repair or correction of equipment or data, you
          assume any costs thereof.
        </p>
        <p className="pt-5 text-gray-700">
          Freelancer will not be responsible for any outcome that may occur
          during the course of usage of our resources. We reserve the rights to
          change prices and revise the resources usage policy at any moment
        </p>
      </div>

      <div className="pt-10">
        <h1 className="text-4xl font-semibold">License</h1>
        <p className="py-5 text-gray-700">
          Freelancer grants you a revocable, non-exclusive, non-transferable,
          limited license to download, install and use the website strictly in
          accordance with the terms of this Agreement.
        </p>
        <p className="py-3 text-gray-700">
          These Terms & Conditions are a contract between you and Freelancer
          (referred to in these Terms & Conditions as “Freelancer”, “us”, “we”
          or “our”), the provider of the Freelancer website and the services
          accessible from the Freelancer website (which are collectively
          referred to in these Terms & Conditions as the “Freelancer Service”).
        </p>
        <p className="py-5 text-gray-700">
          You are agreeing to be bound by these Terms & Conditions. If you do
          not agree to these Terms & Conditions, please do not use the Uptiers
          Service. In these Terms & Conditions, “you” refers both to you as an
          individual and to the entity you represent. If you violate any of
          these Terms & Conditions, we reserve the right to cancel your account
          or block access to your account without notice.
        </p>
      </div>

      <div className="pt-10">
        <h1 className="text-4xl font-semibold">Definitions and key terms</h1>
        <p className="py-5 text-gray-700">
          To help explain things as clearly as possible in this Terms &
          Conditions, every time any of these terms are referenced, are strictly
          defined as:
        </p>
        <ul className="pl-8">
          <li className="py-1 text-gray-700 list-disc ">
            Company: when these terms mention “Company,” “we,” “us,” or “our,”
            it refers to Freelancer Limited, (1, Mission Street, Tedi), that is
            responsible for your information under these Terms & Conditions.
          </li>
          <li className="py-1 text-gray-700 list-disc">
            Country: where Freelancer or the owners/founders of Freelancer are
            based, in this case, is Nigeria.
          </li>
          <li className="py-1 text-gray-700 list-disc">
            {" "}
            Cookie: small amount of data generated by a website and saved by
            your web browser. It is used to identify your browser, provide
            analytics, remember information about you such as your language
            preference or login information.
          </li>
          <li className="py-1 text-gray-700 list-disc">
            Device: any internet-connected device such as a phone, tablet,
            computer, or any other device that can be used to visit Freelancer
            and use the services.
          </li>
          <li className="py-1 text-gray-700 list-disc">
            Service: refers to the service provided by Freelancer as described
            in the relative terms (if available) and on this platform.
          </li>
          <li className="py-1 text-gray-700 list-disc">
            Third-party service: refers to advertisers, contest sponsors,
            promotional and marketing partners, and others who provide our
            content or whose products or services we think may interest you.
          </li>
          <li className="py-1 text-gray-700 list-disc">
            Website: Freelancer’s site, which can be accessed via this URL:
            https://www.freelancer.com
          </li>
          <li className="py-1 text-gray-700 list-disc">
            You: a person or entity that is registered with Freelancer to use
            the Services."
          </li>
        </ul>
      </div>

      <div className="pt-10">
        <h1 className="text-4xl font-semibold">Restrictions</h1>
        <p className="py-5 text-gray-700">
          You agree not to, and you will not permit others to:
        </p>
        <ul className="pl-8">
          <li className="py-1 text-gray-700 list-disc">
            License, sell, rent, lease, assign, distribute, transmit, host,
            outsource, disclose or otherwise commercially exploit the website or
            make the platform available to any third party.
          </li>
          <li className="py-1 text-gray-700 list-disc">
            Modify, make derivative works of, disassemble, decrypt, reverse
            compile or reverse engineer any part of the website.
            <li className="py-1 text-gray-700 list-disc">
              Remove, alter or obscure any proprietary notice (including any
              notice of copyright or trademark) of Uptiers or its affiliates,
              partners, suppliers or the licensors of the website.
            </li>
          </li>
        </ul>
      </div>

      <div className="pt-10">
        <h1 className="text-4xl font-semibold pb-6">Payment</h1>
        <p className="py-1 text-gray-700">
          If you register to any of our recurring payment plans, you agree to
          pay all fees or charges to your account for the Service in accordance
          with the fees, charges, and billing terms in effect at the time that
          each fee or charge is due and payable. Unless otherwise indicated in
          an order form, you must provide Freelancer with a valid credit card
          (Visa, MasterCard, or any other issuer accepted by us) (“Payment
          Provider”) as a condition to signing up for the Premium plan. Your
          Payment Provider agreement governs your use of the designated credit
          card account, and you must refer to that agreement and not these Terms
          to determine your rights and liabilities with respect to your Payment
          Provider. By providing Freelancer with your credit card number and
          associated payment information, you agree that Freelancer is
          authorized to verify information immediately, and subsequently invoice
          your account for all fees and charges due and payable to Freelancer
          hereunder and that no additional notice or consent is required. You
          agree to immediately notify Freelancer of any change in your billing
          address or the credit card used for payment hereunder. Freelancer
          reserves the right at any time to change its prices and billing
          methods, either immediately upon posting on our Site or by e-mail
          delivery to your organization’s administrator(s)
        </p>
        <p className="py-5 text-gray-700">
          Any attorney fees, court costs, or other costs incurred in collection
          of delinquent undisputed amounts shall be the responsibility of and
          paid for by you.
        </p>
        <p className="py-2 text-gray-700">
          No contract will exist between you and for the Service until
          frelancers accepts your order by a confirmatory e-mail, SMS/MMS
          message, or other appropriate means of communication.
        </p>
        <p className="py-5 text-gray-700">
          You are responsible for any third-party fees that you may incur when
          using the Service.
        </p>
      </div>

      <div className="pt-10">
        <h1 className="text-4xl font-semibold ">Return and Refund Policy</h1>
        <p className="pt-5 text-gray-700">
          Thanks for shopping at Uptiers. We appreciate the fact that you like
          to buy the stuff we build. We also want to make sure you have a
          rewarding experience while you’re exploring, evaluating, and
          purchasing our products.
        </p>
        <p className="py-3 text-gray-700">
          As with any shopping experience, there are terms and conditions that
          apply to transactions at Uptiers. We’ll be as brief as our attorneys
          will allow. The main thing to remember is that by placing an order or
          making a purchase at Uptiers, you agree to the terms along with
          Uptiers’s Privacy Policy.
        </p>
        <p className="py-3 text-gray-700">
          If, for any reason, You are not completely satisfied with any good or
          service that we provide, don’t hesitate to contact us and we will
          discuss any of the issues you are going through with our product
        </p>
      </div>

      <div className="pt-10">
        <h1 className="text-4xl font-semibold ">Your Suggestions</h1>
        <p className="pt-5 text-gray-700">
          Any feedback, comments, ideas, improvements or suggestions
          (collectively, “Suggestions”) provided by you to Uptiers with respect
          to the website shall remain the sole and exclusive property of Uptiers
        </p>
        <p className="py-4 text-gray-700">
          Freelancers shall be free to use, copy, modify, publish, or
          redistribute the Suggestions for any purpose and in any way without
          any credit or any compensation to you.
        </p>
      </div>

      <div className="pt-10">
        <h1 className="text-4xl font-semibold ">Your Consent</h1>
        <p className="py-5 text-gray-700">
          We’ve updated our Terms & Conditions to provide you with complete
          transparency into what is being set when you visit our site and how
          it’s being used. By using our website, registering an account, or
          making a purchase, you hereby consent to our Terms & Conditions.
        </p>
      </div>

      <div className="pt-10">
        <h1 className="text-4xl font-semibold ">Links to Other Websites</h1>
        <p className="py-8 text-gray-700">
          This Terms & Conditions applies only to the Services. The Services may
          contain links to other websites not operated or controlled by Uptiers.
          We are not responsible for the content, accuracy or opinions expressed
          in such websites, and such websites are not investigated, monitored or
          checked for accuracy or completeness by us. Please remember that when
          you use a link to go from the Services to another website, our Terms &
          Conditions are no longer in effect. Your browsing and interaction on
          any other website, including those that have a link on our platform,
          is subject to that website’s own rules and policies. Such third
          parties may use their own cookies or other methods to collect
          information about you.
        </p>
      </div>

      <div className="pt-10">
        <h1 className="text-4xl font-semibold ">Cookies</h1>
        <p className="py-5 text-gray-700">
          Freelancers uses “Cookies” to identify the areas of our website that
          you have visited. A Cookie is a small piece of data stored on your
          computer or mobile device by your web browser. We use Cookies to
          enhance the performance and functionality of our website but are
          non-essential to their use. However, without these cookies, certain
          functionality like videos may become unavailable or you would be
          required to enter your login details every time you visit the website
          as we would not be able to remember that you had logged in previously.
          Most web browsers can be set to disable the use of Cookies. However,
          if you disable Cookies, you may not be able to access functionality on
          our website correctly or at all. We never place Personally
          Identifiable Information in Cookies.
        </p>
      </div>

      <div className="pt-10">
        <h1 className="text-4xl font-semibold pb-4">
          Changes To Our Terms & Conditions
        </h1>
        <p className="py-3 text-gray-700">
          You acknowledge and agree that Uptiers may stop (permanently or
          temporarily) providing the Service (or any features within the
          Service) to you or to users generally at Uptiers’s sole discretion,
          without prior notice to you. You may stop using the Service at any
          time. You do not need to specifically inform Uptiers when you stop
          using the Service. You acknowledge and agree that if Uptiers disables
          access to your account, you may be prevented from accessing the
          Service, your account details or any files or other materials which is
          contained in your account.
        </p>
        <p className="py-5 text-gray-700">
          If we decide to change our Terms & Conditions, we will post those
          changes on this page, and/or update the Terms & Conditions
          modification date below.
        </p>
      </div>
    </div>
  );
}

export default TermCondition;
